package Views;

/**
 *
 * @author niz66
 */
public class HomeUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeUI
     */
    public HomeUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left_panel = new javax.swing.JPanel();
        menu_holder = new javax.swing.JPanel();
        menu_title_holder = new javax.swing.JPanel();
        compare_lbl = new javax.swing.JLabel();
        shadow_btn1 = new javax.swing.JPanel();
        teams_btn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        teams_rdo = new javax.swing.JRadioButton();
        shadow_btn2 = new javax.swing.JPanel();
        players_holder = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        players_rdo = new javax.swing.JRadioButton();
        shadow_btn3 = new javax.swing.JPanel();
        logo_holder = new javax.swing.JPanel();
        legal_lbl = new javax.swing.JLabel();
        logo_lbl = new javax.swing.JLabel();
        shadow = new javax.swing.JLabel();
        right_panel = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(232, 221, 203));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setName("main-window"); // NOI18N

        left_panel.setBackground(new java.awt.Color(3, 101, 100));
        left_panel.setToolTipText("left-panel");
        left_panel.setAlignmentX(0.0F);
        left_panel.setAlignmentY(0.0F);
        left_panel.setMaximumSize(new java.awt.Dimension(300, 800));
        left_panel.setMinimumSize(new java.awt.Dimension(300, 700));
        left_panel.setName("left-panel"); // NOI18N
        left_panel.setPreferredSize(new java.awt.Dimension(300, 800));

        menu_holder.setBackground(left_panel.getBackground());

        menu_title_holder.setBackground(new java.awt.Color(3, 22, 52));
        menu_title_holder.setMaximumSize(new java.awt.Dimension(300, 80));
        menu_title_holder.setMinimumSize(new java.awt.Dimension(300, 80));
        menu_title_holder.setPreferredSize(new java.awt.Dimension(300, 80));

        compare_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/compare.png"))); // NOI18N

        javax.swing.GroupLayout menu_title_holderLayout = new javax.swing.GroupLayout(menu_title_holder);
        menu_title_holder.setLayout(menu_title_holderLayout);
        menu_title_holderLayout.setHorizontalGroup(
            menu_title_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_title_holderLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(compare_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menu_title_holderLayout.setVerticalGroup(
            menu_title_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_title_holderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(compare_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        shadow_btn1.setBackground(new java.awt.Color(3, 54, 73));
        shadow_btn1.setMaximumSize(new java.awt.Dimension(300, 5));
        shadow_btn1.setMinimumSize(new java.awt.Dimension(300, 5));
        shadow_btn1.setPreferredSize(new java.awt.Dimension(300, 5));

        javax.swing.GroupLayout shadow_btn1Layout = new javax.swing.GroupLayout(shadow_btn1);
        shadow_btn1.setLayout(shadow_btn1Layout);
        shadow_btn1Layout.setHorizontalGroup(
            shadow_btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        shadow_btn1Layout.setVerticalGroup(
            shadow_btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        teams_btn.setBackground(new java.awt.Color(3, 54, 73));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teams.png"))); // NOI18N

        teams_rdo.setBackground(teams_btn.getBackground());
        teams_rdo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        teams_rdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teams_rdoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout teams_btnLayout = new javax.swing.GroupLayout(teams_btn);
        teams_btn.setLayout(teams_btnLayout);
        teams_btnLayout.setHorizontalGroup(
            teams_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teams_btnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teams_rdo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        teams_btnLayout.setVerticalGroup(
            teams_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teams_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(teams_btnLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(teams_rdo)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        teams_rdo.getAccessibleContext().setAccessibleName("teams_rdo");

        shadow_btn2.setBackground(menu_title_holder.getBackground());
        shadow_btn2.setMaximumSize(new java.awt.Dimension(300, 5));
        shadow_btn2.setMinimumSize(new java.awt.Dimension(300, 5));

        javax.swing.GroupLayout shadow_btn2Layout = new javax.swing.GroupLayout(shadow_btn2);
        shadow_btn2.setLayout(shadow_btn2Layout);
        shadow_btn2Layout.setHorizontalGroup(
            shadow_btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        shadow_btn2Layout.setVerticalGroup(
            shadow_btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        players_holder.setBackground(teams_btn.getBackground());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/players.png"))); // NOI18N

        players_rdo.setBackground(teams_rdo.getBackground());
        players_rdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                players_rdoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout players_holderLayout = new javax.swing.GroupLayout(players_holder);
        players_holder.setLayout(players_holderLayout);
        players_holderLayout.setHorizontalGroup(
            players_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(players_holderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(players_rdo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        players_holderLayout.setVerticalGroup(
            players_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(players_holderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(players_holderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(players_rdo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        shadow_btn3.setBackground(shadow_btn2.getBackground());
        shadow_btn3.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout shadow_btn3Layout = new javax.swing.GroupLayout(shadow_btn3);
        shadow_btn3.setLayout(shadow_btn3Layout);
        shadow_btn3Layout.setHorizontalGroup(
            shadow_btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        shadow_btn3Layout.setVerticalGroup(
            shadow_btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menu_holderLayout = new javax.swing.GroupLayout(menu_holder);
        menu_holder.setLayout(menu_holderLayout);
        menu_holderLayout.setHorizontalGroup(
            menu_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_title_holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shadow_btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(teams_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shadow_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(players_holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shadow_btn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        menu_holderLayout.setVerticalGroup(
            menu_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_holderLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(menu_title_holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(shadow_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teams_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(shadow_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(players_holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(shadow_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );

        logo_holder.setBackground(left_panel.getBackground());

        legal_lbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        legal_lbl.setForeground(new java.awt.Color(3, 54, 73));
        legal_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        legal_lbl.setText("19/20 statistics provided by www.eliteleague.co.uk");

        logo_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        javax.swing.GroupLayout logo_holderLayout = new javax.swing.GroupLayout(logo_holder);
        logo_holder.setLayout(logo_holderLayout);
        logo_holderLayout.setHorizontalGroup(
            logo_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(legal_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(logo_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logo_holderLayout.setVerticalGroup(
            logo_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logo_holderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(legal_lbl)
                .addContainerGap())
        );

        javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
        left_panel.setLayout(left_panelLayout);
        left_panelLayout.setHorizontalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo_holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu_holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        left_panelLayout.setVerticalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_panelLayout.createSequentialGroup()
                .addComponent(menu_holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo_holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        shadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shadow.png"))); // NOI18N
        shadow.setAlignmentY(0.0F);
        shadow.setMinimumSize(new java.awt.Dimension(20, 700));
        shadow.setName("shadow"); // NOI18N

        right_panel.setToolTipText("right-panel");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pie.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout right_panelLayout = new javax.swing.GroupLayout(right_panel);
        right_panel.setLayout(right_panelLayout);
        right_panelLayout.setHorizontalGroup(
            right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        right_panelLayout.setVerticalGroup(
            right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(left_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(shadow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(right_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(left_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shadow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(right_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void teams_rdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teams_rdoActionPerformed
        //create new instance of teams ui    
        TeamsUI teamsUI = new TeamsUI();
        //close this view
        this.dispose();
        //open the teams view & set it to visible
        teamsUI.setVisible(true);
    }//GEN-LAST:event_teams_rdoActionPerformed

    private void players_rdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_players_rdoActionPerformed
        //create new instance of players ui    
        PlayersUI playersUI = new PlayersUI();
        //close this view
        this.dispose();
        //open the teams view & set it to visible
        playersUI.setVisible(true);
    }//GEN-LAST:event_players_rdoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel compare_lbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel left_panel;
    private javax.swing.JLabel legal_lbl;
    private javax.swing.JPanel logo_holder;
    private javax.swing.JLabel logo_lbl;
    private javax.swing.JPanel menu_holder;
    private javax.swing.JPanel menu_title_holder;
    private javax.swing.JPanel players_holder;
    private javax.swing.JRadioButton players_rdo;
    private javax.swing.JPanel right_panel;
    private javax.swing.JLabel shadow;
    private javax.swing.JPanel shadow_btn1;
    private javax.swing.JPanel shadow_btn2;
    private javax.swing.JPanel shadow_btn3;
    private javax.swing.JPanel teams_btn;
    private javax.swing.JRadioButton teams_rdo;
    // End of variables declaration//GEN-END:variables
}
